version: '3.7'

services:
  orion-api:
    container_name: orion-api
    image: orion-api:dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:4444
    command: npm run start:dev
    environment:
      NODE_ENV: ${NODE_ENV}
      SERVER_PORT: ${SERVER_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      OAUTH_CLIENTID: ${OAUTH_CLIENTID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      BLOGGER_API_URL: ${BLOGGER_API_URL}
    networks:
      - orion-connect
  
  orion-mongo:
    container_name: orion-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ~/docker/volumes/OrionApi_MongoDB:/data/db
    networks:
      - orion-connect
    logging:
      driver: none

networks:
  orion-connect:
    driver: bridge
    