version: '3.7'

services:
  orion-api:
    container_name: orion-api
    image: orion-api:dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:4444
    command: npm run start:dev
    environment:
      NODE_ENV: development
      SERVER_PORT: 4444
      DB_DATABASE: orion
      DB_CONNECTION_STRING: mongodb://orion_root:j5m966qp7jiypfda@orion-mongo:27017
      JWT_SECRET: AFdMvt5jwI5n9LNHN0MxPxLWm9nwtsb8M2Q9yYBYzbRGz03ris
      FRONTEND_URL: http://localhost:8080
    networks:
      - orion-connect
  
  orion-mongo:
    container_name: orion-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: orion_root
      MONGO_INITDB_ROOT_PASSWORD: j5m966qp7jiypfda
      MONGO_INITDB_DATABASE: orion
    ports:
      - 27017:27017
    volumes:
      - ~/docker/volumes/OrionApi_MongoDB:/data/db
    networks:
      - orion-connect
    logging:
      driver: none

networks:
  orion-connect:
    driver: bridge
    